auth:
    resource: "@AuthBundle/Controller/"
    type:     annotation
    prefix:   /

task:
    resource: "@TaskBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /logout
